version: "2"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    network_mode: host

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldock
#    volumes:
#      - '/opt/datasql:/var/lib/mysql'
    network_mode: host

  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host


  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-servcie:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888


  userauthentication:
    image: user-authentication-service:latest
    build: user-authentication/
    restart: always
    network_mode: host
    depends_on:
      - mysql
      - eurekaserver
      - configserver
      - apigateway
    ports:
      - 8090:8090
    expose:
      - 8090


  userregistrationservice:
    image: user-registration-servcie:latest
    build: user-registration-service/
    restart: always
    network_mode: host
    ports:
      - 8805:8805
    expose:
      - 8805
#
#  mongodb:
#    image: mongo:3.4-jessie
#    container_name: "RegistrationDB"
#    ports:
#      - 27017:27017

  productservice:
    image: product-servcie:latest
    build: product-service/
    restart: always
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8881:8881
    expose:
      - 8881

  recommendation-service:
    image: recommendation-service:latest
    build: recommendation-service/
    restart: always
    network_mode: host
#    depends_on:
#      - neo4j
    ports:
      - 8086:8086
    expose:
      - 8086

  ontrackFrontend:
    build: OntrackFrontend/
    image: ontrack-front-end
    container_name: ontrack-front-end
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200
    restart: always
